### ISSUE TITLE
PROTOTIPO

### ISSUE THREAD

**Issue by MariaJose-1007** [SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-equipo-magaly#1]
[PROTOTIPO REALIDAD AUMENTADA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-equipo-magaly/files/14314897/PROTOTIPO.REALIDAD.AUMENTADA.pdf)

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by IrvingFernand0** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
